package rules

import java.util.Map
import java.util.HashMap

// Объявляем тип факта
declare Person
    name : String
    age : int
    adult : boolean
end

// Правило 1: Определение совершеннолетия
rule "Check Adult"
    when
        $p : Person(age >= 18, adult == false)
    then
        modify($p) {
            setAdult(true)
        };
        System.out.println("Person " + $p.getName() + " is adult");
end

// Правило 2: Приветствие
rule "Greet Person"
    when
        $p : Person(name != null)
    then
        System.out.println("Hello, " + $p.getName() + "!");
end